### ISSUE TITLE
Create docs page Reference/Infrastructure/GitHub/Repositories (Part 2 -- Repositories)

### ISSUE THREAD

**Issue by DFriend01** [UBCSailbot/docs#100]
### Purpose

Document GitHub infrastructure. This issue focuses on GitHub repositories.

### Page Tree

```yml
nav:
  ...
  - Reference:
    - Infrastructure:
        - GitHub:
          - Repositories:
            - The .github Repository: reference/infrastructure/github/repositories/dot_github.md
            - Repository Setup and Management: reference/infrastructure/github/repositories/repo_setup_manage.md
              ...
```

### Topics

- .github Repository
  - Issue templates
  - PR template
- Repository Setup and Management
  - Template Repositories (do we have any at this point?)
  - Recommended repository settings
  - CODEOWNERS
  - Access permissions (by team)

### Resources

- [GitHub Templates Docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)
- [GitHub Repo Docs](https://docs.github.com/en/repositories)
