### ISSUE TITLE
Create docs page Reference/Infrastructure/GitHub/Features (Part 3 -- Advanced Features)

### ISSUE THREAD

**Issue by DFriend01** [UBCSailbot/docs#101]
### Purpose

Document GitHub infrastructure. Document more advanced features that may require more documentation specific details for what we implemented.

### Page Tree

```yml
nav:
  ...
  - Reference:
    - Infrastructure:
      - GitHub:
        - Features:
            - Actions: reference/github/infrastructure/actions.md
            - Packages: reference/github/infrastructure/packages.md
          ...
```

### Topics

- Actions
  - Creating actions (from others and make our own custom actions)
  - Our custom linter(s): Hyperlink Linter
- Packages
  - Sailbot Workspace packages 

### Resources

- [Custom Actions](https://docs.github.com/en/actions/creating-actions/about-custom-actions)
- [Custom Hyperlink Linter](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)
- [Packages](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)
