### ISSUE TITLE
Update docs structure Reference/GitHub

### ISSUE THREAD

**Issue by DFriend01** [UBCSailbot/docs#104]
### Purpose

GitHub is mostly used as part of our infrastructure, so we should move the content to a more appropriate location.

### Changes

Move the GitHub page, both in the filesystem and in the website page structure. Remember to check for broken links that may result in moving this folder to a new location (mostly images in the GitHub folder and links to any workflow content).

**Current Location:** `reference/github`
**New Location:** `reference/infrastructure/github`

### Updated Page Tree
```yml
nav:
  ...
- Reference:
    - reference/index.md
    ...
    - Infrastructure:
      - GitHub:
        - Development Workflow:
          - Overview:
            - reference/infrastructure/github/workflow/index.md
          - Creating Issues: reference/infrastructure/github/workflow/issues.md
          - Developing on Branches: reference/infrastructure/github/workflow/branches.md
          - Pull Requests: reference/infrastructure/github/workflow/pr.md
    ...
```
