### ISSUE TITLE
Create docs page Reference/ROS/Testing

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/docs#132]
@DFriend01 created this issue as a placeholder, we can fill it out when we have time

### Page Tree

```yml
nav:
  ...
  - _Section_:
    ...
    - _Page_: _section_/_page_.md
```

### Topics

- 

### Resources

-
