### ISSUE TITLE
Create docs page Reference/GitHub/Workflow

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/docs#23]
### Purpose
Document GitHub workflow

### Page Tree
```yml
nav:
  ...
  - Reference:
    ...
    - GitHub:
      - Workflow: reference/github/workflow.md
```

### Contents
- Creating issue
    - Using issue templates (or creating from scratch)
    - Adding to project
    - Adding labels (label conventions)
    - Adding assignees
- Creating branch, pushing commits
    - Include Git commands
- Creating PR
    - Linking issue or adding to project
    - Adding labels (label conventions)
    - Adding reviewers
    - Create as draft until ready to be reviewed
- Merging into master
    - Requirements
        - Pass CI
        - Approved by reviewers

### Relevant Resources
- https://patrick-5546.github.io/notes/reference/git/git_contributing/
- https://patrick-5546.github.io/notes/reference/git/git_commands/
