### ISSUE TITLE
GitHub Infrastructure Page Creation Tracker

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/docs#24]
### Purpose
Document GitHub infrastructure

#### Page Tree
```yml
nav:
  ...
  - Reference:
    ...
    - Infrastructure:
      - GitHub:
        - Development Workflow:
          ...
        - Features:
          ...
        - Repositories:
          ...
      ...
```

#### Tasks
- [ ] https://github.com/UBCSailbot/docs/issues/103 -- **must be done before next item in list**
- [ ] https://github.com/UBCSailbot/docs/issues/104 -- **must be done before next item in list**
- [ ] https://github.com/UBCSailbot/docs/issues/99
- [ ] https://github.com/UBCSailbot/docs/issues/100
- [ ] https://github.com/UBCSailbot/docs/issues/101

### Relevant Resources
- Google Docs
    -  GitHub Organization
- Confluence
    - Infrastructure meeting notes
