### ISSUE TITLE
Create docs page _section_/_page_

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/docs#26]
### Page Tree
```yml
nav:
  ...
  - _Section_:
    ...
    - _Page_: _section_/_page_.md
```

### Contents
- 

### Relevant Resources
-
