### ISSUE TITLE
Create docs page Reference/Material for MkDocs

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/docs#27]
### Purpose
What you would need to know to contribute to our documentation sites

### Page Tree
```yml
nav:
  ...
  - Reference:
    ...
    - Material for MkDocs: reference/material-for-mkdocs.md
```

### Contents
- Relevant files
    - docs/
    - mkdocs.yml
        - Page tree
- Reference demo/syntax
- GitHub pages integration
   - GitHub actions
   - Repository setup

### Relevant Resources
- https://patrick-5546.github.io/notes/reference/mkdocs/
- https://squidfunk.github.io/mkdocs-material/reference/
