### ISSUE TITLE
Create docs page Reference/Python

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/docs#28]
### Purpose
Document Python conventions and libraries

### Page Tree
```yml
nav:
  ...
  - Reference:
    ...
    - Python: Reference/python.md
```

### Contents
- Conventions
    - PEP 8, flake8
        - File structure: imports, constants, main function, helper functions, `if __name__ == '__main__':`
    - camelcase vs underscores
- Virtual environments
    -  requirements.txt
        - explore https://github.com/bndr/pipreqs
    - [ ] Point virtual environment link in main README.md to this page

### Relevant Resources
- https://patrick-5546.github.io/notes/reference/python/
