### ISSUE TITLE
Create docs page Reference/Sailing

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/docs#30]
### Purpose
Important sailing knowledge and terms to know

### Page Tree
```yml
nav:
  ...
  - Reference:
    ...
    - Sailing: reference/sailing.md
```

### Contents
- Consult one of our sailing experts (ideally someone from MECH and SOFT)

### Relevant Resources
-
