### ISSUE TITLE
Create docs page Reference/Markdown

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/docs#36]
### Purpose
Markdown syntax for GitHub (README, issues, PR's)

### Page Tree
```yml
nav:
  ...
  - Reference:
    ...
    - Markdown: reference/markdown.md
```

### Resources
- https://www.markdownguide.org/getting-started/
- https://docs.github.com/en/get-started/writing-on-github
