### ISSUE TITLE
Create docs page Reference/C++

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/docs#37]
### Purpose
Document C++ conventions and libraries

### Page Tree
```yml
nav:
  ...
  - Reference:
    ...
    - C++: Reference/cpp.md
```

### Topics
- TBD

### Resources
- TBD
