### ISSUE TITLE
Create docs page New Project

### ISSUE THREAD

**Issue by patrick-5546** [UBCSailbot/docs#85]
### Purpose
Introduction to new project

### Page Tree
```yml
nav:
  ...
  - _Section_:
    ...
    - _Page_: _section_/_page_.md
```

### Topics
- Cleaned up version of first resource
- Software system demo video/gif

### Resources
- https://ubcsailbot.atlassian.net/wiki/spaces/prjt22/pages/1722253342/Software-Wide+New+Project+Planning
