### ISSUE TITLE
Create docs page Reference/Infrastructure/GitHub/Features (Part 1 -- Basic Features)

### ISSUE THREAD

**Issue by DFriend01** [UBCSailbot/docs#99]
### Purpose

Document GitHub infrastructure. Document some basic information that we can easily link to the github docs for.

### Page Tree

```yml
nav:
  ...
  - Reference:
    - Infrastructure:
      ...
        - GitHub:
          - Features:
              - Projects: reference/infrastructure/github/features/projects.md
              - Teams: reference/infrastructure/github/features/teams.md
              ...
```

### Topics

- Projects
- Releases
- Teams
- Organization
- Milestones

### Resources

- [The GitHub Docs](https://docs.github.com/en) -- all of these topics are discussed on there.
- [The Sailbot Org](https://github.com/UBCSailbot)
